FROM node:18 as build-stage

WORKDIR /app

ARG VITE_APP_BACKEND_API_URL
ENV VITE_APP_BACKEND_API_URL=${VITE_APP_BACKEND_API_URL}

COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM nginx:alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
