version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: - #Введите пароль
      MYSQL_DATABASE: qugor_arts
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 3500:80
    environment:
      - PMA_ARBITRARY=1

  bot:
    depends_on:
      - db
    build: ./bot
    ports:
      - 5000:5000

  admin-panel:
    build: ./admin-panel
    depends_on:
      - bot
    ports:
      - 80:80
