version: "3.8"

networks:
  dev:


services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      MY_DOMAIN: ${MY_DOMAIN}
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - './data/certbot/www:/var/www/certbot'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - dev




  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_ADMIN_USER}
      MYSQL_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
    ports:
      - 3306:3306
    command: --init-file /data/application/sql.ini
    volumes:
      - ./sql.ini:/data/application/sql.ini
      - ./data/backups:/backups
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3500:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    networks:
      - dev

  bot:
    depends_on:
      - db
    build:
      context: ./bot
    restart: unless-stopped
    networks:
      - dev
    env_file:
      - .env


  frontend:
    build:
      context: ./frontend
      args:
        VITE_APP_BACKEND_API_URL: ${VITE_APP_BACKEND_API_URL}
    depends_on:
      - bot
    restart: unless-stopped
    networks:
      - dev
    env_file:
      - .env
