version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: // Пароль
      MYSQL_DATABASE: //БД
    ports:
      - 3306:3306
    command: --init-file /data/application/sql.ini
    volumes:
      - ./sql.ini:/data/application/sql.ini

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 3500:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M

  bot:
    depends_on:
      - db
    build: ./bot-nest
    ports:
      - 5000:5000

  frontend:
    build: ./frontend
    depends_on:
      - bot
    ports:
      - 80:80
