version: "3.8"

networks:
    dev:


services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
            - '/etc/letsencrypt:/etc/letsencrypt'
            - './data/certbot/www:/var/www/certbot'
        depends_on:
            - bot
            - frontend
        networks:
            - dev
        restart: unless-stopped
        env_file:
            - .env

    db:
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_ADMIN_USER}
            MYSQL_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
        ports:
            - 3306:3306
        command: --init-file /data/application/sql.ini
        volumes:
            - ./sql.ini:/data/application/sql.ini
            - ./data/backups:/backups
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - db
        restart: unless-stopped
        ports:
            - 3500:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=300M
        networks:
            - dev

    bot:
        depends_on:
            - db
        build:
            context: ./bot
        restart: unless-stopped
        networks:
            - dev

    frontend:
        build:
            context: ./frontend
        depends_on:
            - bot
        restart: unless-stopped
        networks:
            - dev

