version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SaoTop123
      MYSQL_DATABASE: qugor-arts
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3500:80
    environment:
      - PMA_ARBITRARY=1

  bot:
    depends_on:
      - db
    build: ./bot
    ports:
      - 5000:5000

  admin-panel:
    build: ./admin-panel
    ports:
      - 80:80
