version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SaoTop123
      MYSQL_DATABASE: qugor-arts
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3500:80
    environment:
      - PMA_ARBITRARY=1

  bot:
    build: ./bot
    ports:
      - 5000:5000

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./vue-app:/usr/share/nginx/html

  admin-panel:
    build: ./admin-panel
    ports:
      - 8080:80
