FROM node:14 as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:14

WORKDIR /app

COPY --from=build-stage /app/dist /app/dist

EXPOSE 8080

CMD ["npm", "run", "start"]
