# FROM node:alpine as build
# WORKDIR /app
# COPY . .
# RUN npm install
# RUN npm run build

# # production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/dist /usr/share/nginx/html
# COPY --from=build /app/nginx.conf /etc/nginx/sites-enabled/default
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

# Используем официальный Node.js образ как базовый
FROM node:18

# Создаем рабочую директорию в контейнере
WORKDIR /app

# Копируем package.json и package-lock.json (или yarn.lock) в рабочую директорию
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код приложения в рабочую директорию
COPY . .

# Собираем Vue приложение
RUN npm run build

# Указываем, что порт 8080 будет использоваться для приложения
EXPOSE 80

# Запускаем сервер для обслуживания статических файлов
CMD ["npx", "serve", "-s", "dist", "-l", "80"]
