# Используем базовый образ с Node.js
FROM node:alpine AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем файлы проекта
COPY . .

# Собираем приложение
RUN npm run build

# Отдельный этап, чтобы уменьшить размер образа
FROM nginx:alpine

# Копируем собранные файлы Vue.js приложения в образ Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Порт, который будет использоваться контейнером
EXPOSE 80

# Команда запуска nginx внутри контейнера
CMD ["nginx", "-g", "daemon off;"]
